[versions]
apache-commons-csv = "1.14.1"
java-languageVersion = "21"
kotlin = "2.3.0"
kotlinx-serialization = "1.10.0"
ktlint = "1.8.0"
mockito-kotlin = "6.2.3"
mysql = "9.6.0"
spring-dependency-management = "1.1.7"
springframework-boot = "4.0.2"

[libraries]
apache-commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "apache-commons-csv" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
springframework-boot = { id = "org.springframework.boot", version.ref = "springframework-boot" }
